global_refresh_interval: 10
favicon: bitcoin
show_latency: true
bitcoin_core:
    enabled: true
    rpc_address: http://192.168.0.211:8332
    rpc_user: satoshi
    rpc_password: satoshi
    clearnet_address: ""
    tor_address: ""
    title_link: ""
    recent_blocks_count: 30
mempool:
    enabled: true
    api_endpoint: http://192.168.0.211:4080
    title_link: ""
    subsat: true
fulcrum:
    enabled: true
    rpc_address: 192.168.0.211
    rpc_port: 50001
    ssl_enabled: false
    clearnet_address: ""
    tor_address: ""
    title_link: ""
monero:
    enabled: true
    rpc_address: http://192.168.0.211:18089
    title_link: ""
    recent_blocks_count: 30
notifications:
    gotify_url: http://truenas.local:4040/
    gotify_token: AdvkEOWFAjiRzyU
    enabled: true
    check_freq: 60
